language: node_js
node_js:
  - "6"

addons:
  firefox: "latest"

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/logs

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./scripts/sauce_*.sh

before_script:
  - npm run typings
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh

script:
  - npm run lint
  - ./scripts/sauce_connect_block.sh
  - npm test

after_script:
  - ./scripts/sauce_connect_teardown.sh

sudo: false
